### ISSUE TITLE
Typo : update_all.sh => update_all.ini

### ISSUE THREAD

**Issue by Saroumane** [theypsilon/Updater_script_MiSTer_Unofficial#2]
Hello, there is a typo at the end of README : the "update_all.sh" in blue should be "update_all.ini"
![image](https://user-images.githubusercontent.com/22261137/103389973-4be93000-4b12-11eb-97ff-154133a3735a.png)

**Comment by theypsilon** [comment]
Good catch, thank you! Fixed

**Comment by Saroumane** [comment]
Thanks to you, your script is very useful !
